#!/bin/bash

## MYSQL server configuration
MYSQL_ROOT_PASSWORD=password
MYSQL_DATABASE=ecstore
MYSQL_USER=ecstore
MYSQL_PASSWORD=password

## ECSTORE configuration
ECSTORE_SOURCE=
ECSTORE_MARIADB=${ECSTORE_MARIADB:-ecstore-mariadb}
ECSTORE_MARIADB_VOLUME=${ECSTORE_MARIADB_VOLUME:-ecstore-mariadb-volume}
MARIADB_IMAGE=${MYSQL_IMAGE:-mariadb}
ECSTORE_NAME=${ECSTORE_NAME:-ecstore}
ECSTORE_IMAGE=${ECSTORE_IMAGE:-tcic/ecstore}
NGINX_NAME=${NGINX_NAME:-proxy}
NGINX_IMAGE_NAME=${NGINX_IMAGE_NAME:-nginx}

## The MAC address is generated using the IP address allocated to the container to avoid ARP collisions,
## using a range from 02:42:ac:11:00:00 to 02:42:ac:11:ff:ff.
MAC_ADDRESS=02:42:ac:11:ff:ff
